name: Update Components

on:
  workflow_dispatch: # Run daily

jobs:
  update-components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest Karpenter release version
        id: get-karpenter-version
        run: |
          latest_release=$(curl -s https://api.github.com/repos/aws/karpenter/releases/latest | jq -r '.tag_name')
          echo "::set-output name=version::$latest_release"

      - name: Update components.json
        run: |
          latest_version="${{ steps.get-karpenter-version.outputs.version }}"
          jq --arg latest_version "$latest_version" '.karpenter = $latest_version' components.json > updated.json
          mv updated.json components.json

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b PR
          git add components.json
          git commit -m "Update Karpenter version to ${{ steps.get-karpenter-version.outputs.version }}"
          git push origin PR

      - name: Create Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.DEPENDA }}
          script: |
            const baseBranch = 'main';  // Replace with your base branch name
            const headBranch = 'PR';  // Replace with your feature branch name
            console.log(`Creating pull request from ${headBranch} to ${baseBranch}`);
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Update Karpenter version to ${{ steps.get-karpenter-version.outputs.version }}",
              body: "This PR updates the Karpenter version to ${{ steps.get-karpenter-version.outputs.version }}.",
              base: baseBranch,
              head: headBranch,
            });
            
      - name: Get Kube-Proxy Version
        id: get-version
        run: |
          # Use curl to fetch the AWS EKS documentation page
          documentation_url="https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html"
          documentation_content=$(curl -s "$documentation_url")

          # Use grep to extract the kube-proxy version
          kube_proxy_version=$(echo "$documentation_content" | grep -oE 'kube-proxy minimal version\s*([0-9]+\.[0-9]+\.[0-9]+)')

          if [ -z "$kube_proxy_version" ]; then
            echo "Failed to retrieve kube-proxy version."
            exit 1
          fi

          # Output the version as an action output
          echo "::set-output name=version::$kube_proxy_version"

