name: Extract Kube-Proxy Version

on:
  workflow_dispatch:  # Trigger the workflow manually

jobs:
  extract-kube-proxy-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y curl jq
        shell: bash

      - name: Extract Kube-Proxy Version
        run: |
          # Replace this URL with the actual AWS EKS documentation URL for kube-proxy version.
          url="https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html"

          # Use curl to fetch the web page content and pipe it to grep to find the relevant section.
          content=$(curl -s "$url" | grep -A 5 "Kubernetes 1.27" | sed -n '2p;5p' | awk '{print $1}')

          if [ -n "$content" ]; then
            kube_proxy_version=$(echo "$content" | jq -sRr '@text')
          else
            kube_proxy_version="Version not found"
          fi

          echo "Kube-Proxy Version: $kube_proxy_version"
