name: Test

on:
  pull_request:
    branches: 
      - "main"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
#    if: contains(github.event.pull_request.changed_files, 'components.json')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
      - name: List all changed files
        id: files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  mirror:
    runs-on: ubuntu-latest
    needs: check
#    if: contains(needs.check.outputs.matrix, 'components.json')
    steps:
      - name: checks file exist
        run: |
          echo "successfully done"
          echo "${{contains(needs.check.outputs.matrix, 'components.json')}}"
          
  build:
    runs-on: ubuntu-latest
    needs: mirror
    if : ${{ !failure() }}
    steps:
      - name: echoing
        run: |
          echo "${{needs.mirror.result}}"
          echo "2nd job ran success"
