name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - "main"

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'components.json')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    needs: mirror
    if : ${{ needs.mirror.result == 'success' || needs.mirror.result == 'skipped' }}
    steps:
      - name: echoing
        run: |
          echo "2nd job ran success"
