name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - "main"

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'components.json')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  build:
    needs: mirror
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
