name: Test

on:
  pull_request:
    branches: 
      - "main"

jobs:
  mirror:
    runs-on: ubuntu-latest
#    if: contains(github.event.pull_request.changed_files, 'components.json')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: count files
        run: |
          echo "${{github.event.pull_request.changed_files}}"
          echo "${{ contains(github.event.pull_request.changed_files, '*components.json*') }}"
          echo "1st job ran success"
          echo "${{ contains(github.event.pull_request.changed_files, '*test.yml*') }}"
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  build:
    runs-on: ubuntu-latest
    needs: mirror
    if : ${{ needs.mirror.result == 'success' || needs.mirror.result == 'skipped' }}
    steps:
      - name: echoing
        run: |
          echo "${{needs.mirror.result}}"
          echo "2nd job ran success"
